image: python:3.13

stages:
  - test
  - deploy

variables:
  CELERY_BROKER_URL: "redis://redis:6379/0"
  DJANGO_SETTINGS_MODULE: "config.settings"

before_script:
  - python --version
  - pip install --upgrade pip
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

test:
  stage: test
  services:
    - name: redis:7-alpine
      alias: redis
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - python manage.py migrate
    - python -m pytest -v --tb=short

deploy_to_staging:
  stage: deploy
  script:
    - echo "Ручное развертывание на тестовый стенд..."
    - echo "Приложение успешно развернуто."
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  when: manual
  allow_failure: false
